# List of all the books title with movie releases.

movie_titles = ["Big Little Lies", "Me Before You", "The Circle",
                "Call Me By Your Name", "Everything, Everything",
                "Brooklyn", "A Man Called Ove",
                "Miss Peregrine’s Home for Peculiar Children",
                "The Girl on the Train", "The Light Between Oceans",
                "The 5th Wave", "Still Alice", "The DUFF",
                "Beasts of No Nation", "The Family Fang",
                "This Is Where I Leave You", "Me and Earl and the Dying Girl",
                "The Handmaid's Tale", "The Dinner",
                "Billy Lynn's Long Halftime Walk", "Ender's Game", "If I Stay"]

# List of all the author book list pages on goodreads.com
auth_urls = ["https://www.goodreads.com/author/list/322069.Liane_Moriarty",
             "https://www.goodreads.com/author/list/281810.Jojo_Moyes",
             "https://www.goodreads.com/author/list/3371.Dave_Eggers",
             "https://www.goodreads.com/author/list/2922229.Andr_Aciman",
             "https://www.goodreads.com/author/list/7353006.Nicola_Yoon",
             "https://www.goodreads.com/author/list/1351903.Colm_T_ib_n",
             "https://www.goodreads.com/author/list/6485178.Fredrik_Backman",
             "https://www.goodreads.com/author/list/3046613.Ransom_Riggs",
             "https://www.goodreads.com/author/list/1063732.Paula_Hawkins",
             "https://www.goodreads.com/author/list/5755257.M_L_Stedman",
             "https://www.goodreads.com/author/list/3377941.Rick_Yancey",
             "https://www.goodreads.com/author/list/978484.Lisa_Genova",
             "https://www.goodreads.com/author/list/3095919.Kody_Keplinger",
             "https://www.goodreads.com/author/list/27161.Uzodinma_Iweala",
             "https://www.goodreads.com/author/list/73187.Kevin_Wilson",
             "https://www.goodreads.com/author/list/26163.Jonathan_Tropper",
             "https://www.goodreads.com/author/list/5227163.Jesse_Andrews",
             "https://www.goodreads.com/author/list/3472.Margaret_Atwood",
             "https://www.goodreads.com/author/list/1245772.Herman_Koch",
             "https://www.goodreads.com/author/list/7079.Ben_Fountain",
             "https://www.goodreads.com/author/list/589.Orson_Scott_Card",
             "https://www.goodreads.com/author/list/295178.Gayle_Forman"]
